name: Compile Extensions

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      
    - name: Init Submodules
      run: git submodule update --init --recursive --checkout
      
    - name: Generate Matrix
      id: matrix
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        pr_paths=$(gh pr view ${{ github.event.pull_request.number }} --json files -q '.files[].path' 2> /dev/null || true)
        git submodule --quiet foreach "
          paths=\"$pr_paths\"
          if [ -z \"$paths\" ]; then
            paths=\"\$displaypath\"
          fi
          case \$displaypath in 
            \$paths)
              echo \$(git remote get-url origin | sed 's/https:\/\/github\.com\///' | sed 's/\.git//') \$sha1 \$displaypath
              ;;
          esac" | \
          awk 'NR > 1 {printf(",")} {printf("{\"repository\":\"%s\",\"ref\":\"%s\",\"path\":\"%s\"}", $1, $2, $3)}' | \
          cat <(echo -n 'value=[') - <(echo -n ']')  >> $GITHUB_OUTPUT
      
    - name: Check matrix value
      run: echo "${{ steps.matrix.outputs.value }}"

  build:
    name: "Build"
    needs: [ setup ]
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.build_extension.outputs.artifact-name }}
      artifact-path: ${{ steps.build_extension.outputs.artifact-path }}
      manifest: ${{ steps.build_extension.outputs.manifest }}
    strategy:
      fail-fast: false
      matrix:
        value: ${{ fromJson(needs.setup.outputs.matrix) }}
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      
    - name: Init Submodule
      run: git submodule update --init --recursive ${{ matrix.value.path }}
      
    - name: Build Extension
      id: build_extension
      uses: Macro-Deck-App/Actions/build-extension@main
      with:
        ext-repo: ${{ matrix.value.repository }}
        ext-ref: ${{ matrix.value.ref }}
            
  deploy:
    name: "Deploy"
    needs: [ build ]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          # Artifact name
          name: ${{ needs.build.outputs.artifact-name }}
      
      - name: Upload built files
        id: upload-build-files
        env:
          MACRO_DECK_API_AUTH: "${{ secrets.MACRO_DECK_API_TOKEN }}"
        run: |
          curl --fail-with-body -o "./${{ fromJSON(needs.build.outputs.manifest).packageId }}-upload-response.json" -X POST \
            '${{ vars.EXTENSION_STORE_API_URL }}/rest/files/upload' \
            -H 'accept: */*' \
            -H "x-admin-token: $MACRO_DECK_API_AUTH" \
            -H 'Content-Type: multipart/form-data' \
            -F 'file=@${{ needs.build.outputs.artifact-path }};type=application/x-zip-compressed' || true
          response=$(cat "./${{ fromJSON(needs.build.outputs.manifest).packageId }}-upload-response.json")
          echo -e "Response:\n$response"
          echo "response=$(cat "./${{ fromJSON(needs.build.outputs.manifest).packageId }}-upload-response.json")" >> $GITHUB_OUTPUT
      
      - name: Check upload response
        if: |
          fromJSON(steps.upload-build-files.outputs.response).success == false &&
          fromJSON(steps.upload-build-files.outputs.response).errorCode != 4
        run: |
          echo "::error ::Failed to upload files to build server. Response: ${{ steps.upload-build-files.outputs.response }}" && exit 1