name: Plugin Upsert

on:
  workflow_dispatch:
    inputs:
      github_http_url:
        description: 'GitHub Repo HTTP URL'
        required: true
        type: string
      plugin_package_id:
        description: 'Plugin Package ID'
        required: true
        type: string
      plugin_commit_ref:
        description: 'Commit Ref (tag/branch/commit)'
        required: true
        type: string

jobs:
  pull_submodule:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3    
      
      - name: Clean branch
        run: |
          git clean -xfd
          git submodule foreach --recursive git clean -xfd
          git reset --hard
          git submodule foreach --recursive git reset --hard
          git submodule update --init --recursive
          
      - name: Add Submodule (If Needed)
        run: | 
          if [ ! -d "./Plugins/${{ inputs.plugin_package_id }}" ]; then
            git submodule add "${{ inputs.github_http_url }}" "./Plugins/${{ inputs.plugin_package_id }}"
          fi
          
      - name: Update Submodule
        run: |
          cd "./Plugins/${{ inputs.plugin_package_id }}"
          git fetch origin "${{ inputs.plugin_commit_ref }}":"${{ inputs.plugin_commit_ref }}"
          git checkout "${{ inputs.plugin_commit_ref }}"
          cd ../..
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update Plugin ${{ inputs.plugin_package_id }}
          title: '[Plugin Update] ${{ inputs.plugin_package_id }}'
          body: |
            ##Plugin Update
            **Remote URL** ${{ inputs.github_http_url }}
            **Package ID** ${{ inputs.plugin_package_id }}
            **Commit Ref** ${{ inputs.plugin_commit_ref }}
          branch: feature/update-${{ inputs.plugin_package_id }}
